### PR TITLE
Integrate Orchard support

### PR DESCRIPTION
**Pull request by str4d**
Closes Electric-Coin-Company/zcash-android-wallet-sdk#528.
Closes Electric-Coin-Company/zcash-android-wallet-sdk#761.

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [ ] Update **documentation** as appropriate (e.g [README.md](../blob/main/README.md), [Architecture.md](../blob/main/docs/Architecture.md), etc.)
- [x] **Run the demo app** and try the changes
- [ ] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

# Reviewer

- [x] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [ ] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [README.md](../blob/main/README.md), [Architecture.md](/blob/main/docs/Architecture.md), etc. as appropriate
- [x] **Run the demo app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you had to manually test 
something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the demo app to look for build failures or crashes, humans running the demo app are 
more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Review by HonzaR — COMMENTED** [review]
These changes look good to me, although I experience a scan error when syncing blocks: 

```
CompactBlockProcessor.scanBatchOfBlocks$zcash_android_sdk_2_0_8_release(): Failed while scanning batch BlockBatch(order=1, range=BlockHeight(value=1935001)..BlockHeight(value=1935100), blocks=100) with java.lang.RuntimeException: Rust error while scanning blocks (limit 100): The underlying datasource produced the following error: An error occurred accessing or updating note commitment tree data: An error occurred persisting or retrieving tree data: Attempted to write subtree roots with indices 440..441 which is discontinuous with existing subtree range 743..744.
```

It comes from the Rust `scanBlocks()` API. I can not reproduce it on the feature or main branches.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/compare/d31168c2a52df9ea9f29bf3c3f806a5f0695e2a5..e3f89b11caca4f7a47812b3fc1197fb15d8f06ea) to implement the missing Orchard subtree fetch logic.

I'm now getting the following error in the demo app:
```
CompactBlockProcessor.scanBatchOfBlocks$zcash_android_sdk_2_0_8_release(): Failed while scanning batch BlockBatch(order=20, range=BlockHeight(value=2354647)..BlockHeight(value=2354746), blocks=100) with java.lang.RuntimeException:
Rust error while scanning blocks (limit 100):
The underlying datasource produced the following error:
An error occurred accessing or updating note commitment tree data:
An error occurred persisting or retrieving tree data:
Conflict at checkpoint id 2354646, tried to insert Checkpoint { tree_state: AtPosition(Position(48693728)), marks_removed: {} }, which is incompatible with existing state (AtPosition(Position(48693726)), None).
```

**Comment by str4d** [comment]
[Rebased on #1411](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/compare/e3f89b11caca4f7a47812b3fc1197fb15d8f06ea..ad5f0d0060f334daf00b38047c0eeed94f40df3e) after recent `main` was merged back into it.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/compare/ad5f0d0060f334daf00b38047c0eeed94f40df3e..50abc056e59891426da303da7b379406447ce571) to migrate to latest published crate versions, which include bugfixes identified via the Swift SDK.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/compare/ad5f0d0060f334daf00b38047c0eeed94f40df3e..2f104e7f14a16b5ba5da1f0b95eb96346f71eb18) to migrate to latest published crate versions (which include bugfixes identified via the Swift SDK), and to send change to the Orchard pool.

**Review by HonzaR — APPROVED** [review]
utACK, manual tests of sending and receiving will be done in the following review round.

**Review by nuttycom — APPROVED** [review]
utACK 4ee57e40cb2ca689e228a13e3f84a6803d13e639 with non-blocking nits.

**Pull request merged**
